QA Changes
skalenetwork/skale.py pull request #567
Opened 2024-12-23 13:56 UTC by dmytrotkk

WIP - QA Changes

2025-02-07 20:13 UTC, OleksanderSalamatov submitted a review, later dismissed

2025-03-28 16:36 UTC, badrogger requested changes

2025-03-28 16:36 UTC, badrogger commented on skale/contracts/ima/mainnet/community_pool.py
> +    def get_recommended_recharge_amount(self, schain_hash: bytes, receiver: int) -> int:
should be schain_name: str instead.

2025-03-28 16:36 UTC, badrogger commented on skale/contracts/ima/schain/community_locker.py
> +    def time_limit_per_msg(self, schain_hash: bytes) -> int:
should be schain_name: str

2025-03-28 16:36 UTC, badrogger commented on skale/contracts/ima/schain/token_manager_erc1155.py
> +    def get_clones_erc1155(self, schain_hash: bytes, address: str) -> int:
should be schain_name: str

2025-03-28 16:36 UTC, badrogger commented on skale/contracts/ima/schain/token_manager_erc20.py
> +    def get_clones_erc20(self, schain_hash: bytes, address: str) -> int:
should be schain_name: str

2025-03-28 16:36 UTC, badrogger commented on skale/contracts/ima/schain/token_manager_erc721_wmt.py
> +    def get_clones_erc721(self, schain_hash: bytes, address: str) -> int:
should be schain_name: str

2025-04-03 16:55 UTC, merged